export default function PartnersSection() {
  return (
    <div className="elementor-element elementor-element-a94e9e4 e-flex e-con-boxed e-con e-parent e-lazyloaded" data-id="a94e9e4" data-element_type="container" data-e-type="container">
					<div className="e-con-inner">
				<div className="elementor-element elementor-element-a19f429 asset-dm elementor-widget-mobile__width-initial elementor-widget elementor-widget-image" data-id="a19f429" data-element_type="widget" data-e-type="widget" data-widget_type="image.default">
															<img decoding="async" width="786" height="267" src="/assets/media/Met-Business-Partners.png" className="attachment-large size-large wp-image-382" alt="" srcSet="/assets/media/Met-Business-Partners.png 786w, /assets/media/Met-Business-Partners-300x102.png 300w, /assets/media/Met-Business-Partners-768x261.png 768w" sizes="(max-width: 786px) 100vw, 786px" />															</div>
				<div className="elementor-element elementor-element-4f33dda asset-lm elementor-widget-mobile__width-initial elementor-widget elementor-widget-image" data-id="4f33dda" data-element_type="widget" data-e-type="widget" data-widget_type="image.default">
															<img loading="lazy" decoding="async" width="786" height="267" src="/assets/media/Met-Business-Partners-1.png" className="attachment-large size-large wp-image-712" alt="" srcSet="/assets/media/Met-Business-Partners-1.png 786w, /assets/media/Met-Business-Partners-1-300x102.png 300w, /assets/media/Met-Business-Partners-1-768x261.png 768w" sizes="(max-width: 786px) 100vw, 786px" />															</div>
				<div className="elementor-element elementor-element-a9facc5 asset-dm elementor-widget-mobile__width-initial elementor-widget elementor-widget-image" data-id="a9facc5" data-element_type="widget" data-e-type="widget" data-widget_type="image.default">
															<img loading="lazy" decoding="async" width="484" height="342" src="/assets/media/NTDP-Logo-Adjusted.webp" className="attachment-large size-large wp-image-385" alt="" srcSet="/assets/media/NTDP-Logo-Adjusted.webp 484w, /assets/media/NTDP-Logo-Adjusted-300x212.webp 300w" sizes="(max-width: 484px) 100vw, 484px" />															</div>
				<div className="elementor-element elementor-element-b8e3289 asset-lm elementor-widget-mobile__width-initial elementor-widget elementor-widget-image" data-id="b8e3289" data-element_type="widget" data-e-type="widget" data-widget_type="image.default">
															<img loading="lazy" decoding="async" width="484" height="342" src="/assets/media/NTDP-Logo-Adjusted-1.webp" className="attachment-large size-large wp-image-710" alt="" srcSet="/assets/media/NTDP-Logo-Adjusted-1.webp 484w, /assets/media/NTDP-Logo-Adjusted-1-300x212.webp 300w" sizes="(max-width: 484px) 100vw, 484px" />															</div>
				<div className="elementor-element elementor-element-62cf3fe asset-dm elementor-widget-mobile__width-initial elementor-widget elementor-widget-image" data-id="62cf3fe" data-element_type="widget" data-e-type="widget" data-widget_type="image.default">
															<img loading="lazy" decoding="async" width="497" height="122" src="/assets/media/mvplab-tag.png" className="attachment-large size-large wp-image-384" alt="" srcSet="/assets/media/mvplab-tag.png 497w, /assets/media/mvplab-tag-300x74.png 300w" sizes="(max-width: 497px) 100vw, 497px" />															</div>
				<div className="elementor-element elementor-element-e6607fc asset-lm elementor-widget-mobile__width-initial elementor-widget elementor-widget-image" data-id="e6607fc" data-element_type="widget" data-e-type="widget" data-widget_type="image.default">
															<img loading="lazy" decoding="async" width="497" height="122" src="/assets/media/mvplab-tag-1.png" className="attachment-large size-large wp-image-711" alt="" srcSet="/assets/media/mvplab-tag-1.png 497w, /assets/media/mvplab-tag-1-300x74.png 300w" sizes="(max-width: 497px) 100vw, 497px" />															</div>
				<div className="elementor-element elementor-element-582c81e asset-dm elementor-widget-mobile__width-initial elementor-widget elementor-widget-image" data-id="582c81e" data-element_type="widget" data-e-type="widget" data-widget_type="image.default">
															<img loading="lazy" decoding="async" width="250" height="367" src="/assets/media/MiSK_Foundation_logo.svg.png" className="attachment-large size-large wp-image-383" alt="" srcSet="/assets/media/MiSK_Foundation_logo.svg.png 250w, /assets/media/MiSK_Foundation_logo.svg-204x300.png 204w" sizes="(max-width: 250px) 100vw, 250px" />															</div>
				<div className="elementor-element elementor-element-0e76aac asset-lm elementor-widget-mobile__width-initial elementor-widget elementor-widget-image" data-id="0e76aac" data-element_type="widget" data-e-type="widget" data-widget_type="image.default">
															<img loading="lazy" decoding="async" width="698" height="1024" src="/assets/media/MiSK_Foundation_logo.svg-1-698x1024.png" className="attachment-large size-large wp-image-715" alt="" srcSet="/assets/media/MiSK_Foundation_logo.svg-1-698x1024.png 698w, /assets/media/MiSK_Foundation_logo.svg-1-204x300.png 204w, /assets/media/MiSK_Foundation_logo.svg-1-768x1127.png 768w, /assets/media/MiSK_Foundation_logo.svg-1.png 960w" sizes="(max-width: 698px) 100vw, 698px" />															</div>
				<div className="elementor-element elementor-element-2cd1a93 asset-dm elementor-widget-mobile__width-inherit elementor-widget elementor-widget-image" data-id="2cd1a93" data-element_type="widget" data-e-type="widget" data-widget_type="image.default">
															<img loading="lazy" decoding="async" width="357" height="174" src="/assets/media/logo.png" className="attachment-large size-large wp-image-381" alt="" srcSet="/assets/media/logo.png 357w, /assets/media/logo-300x146.png 300w" sizes="(max-width: 357px) 100vw, 357px" />															</div>
				<div className="elementor-element elementor-element-7d237e8 asset-lm elementor-widget-mobile__width-inherit elementor-widget elementor-widget-image" data-id="7d237e8" data-element_type="widget" data-e-type="widget" data-widget_type="image.default">
															<img loading="lazy" decoding="async" width="864" height="420" src="/assets/media/garage-logo.png" className="attachment-large size-large wp-image-714" alt="" srcSet="/assets/media/garage-logo.png 864w, /assets/media/garage-logo-300x146.png 300w, /assets/media/garage-logo-768x373.png 768w" sizes="(max-width: 864px) 100vw, 864px" />															</div>
					</div>
				</div>
  );
}
